torrent/urls.py
from django.urls import path
from .views import TorrentList, TorrentDetail, download_torrent, UploadTorrentView
from . import views


urlpatterns = [
    path('', TorrentList.as_view(), name = "torrent_list"),
    path("search/", views.search, name= "search"),
    path('upload/', UploadTorrentView.as_view(), name="upload_torrent"),
    path('<int:pk>', TorrentDetail.as_view(), name = "torrent_detail"),
    path('download/<int:torrent_id>/', download_torrent, name='download_torrent'),  
]
    

torrents_server/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from torrent.views import HomeView, UploadTorrentView



urlpatterns = [
    path('', HomeView.as_view()),
    path('admin/', admin.site.urls),
    path('torrent/', include('torrent.urls')),
    path('upload/', UploadTorrentView.as_view(), name="upload_torrent"),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

torrent/models.py
from django.db import models

# Create your models here.


LANGUAGES_CHOICES={
    ("EN","ENGLISH"),
    ("CS","CASTELLANO"),
    ("FR","FRENCH"),
}


class torrent(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=200)
    image = models.ImageField(upload_to="torrents")
    language = models.CharField(choices=LANGUAGES_CHOICES,max_length=2)
    date = models.DateField()
    torrent_file = models.FileField(unique=True, null=True,upload_to='torrents')
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    
    

torrent/forms.py
from django import forms
from .models import torrent

class TorrentForm(forms.ModelForm):
    class Meta:
        model = torrent
        fields = ['title', 'description', 'image', 'language', 'date', 'torrent_file']

torrent/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from torrent.forms import TorrentForm
from .models import torrent
from django.shortcuts import get_object_or_404
from django.http import FileResponse
from django.urls import reverse_lazy
from django.views.generic.edit import FormView





#class TorrentList(ListView):
 #   model = torrent
    #context_object_name = ""
    #template_name = ""



class UploadTorrentView(FormView):
    template_name = 'torrent/upload_torrent.html'  # Asegúrate de tener una plantilla llamada upload_torrent.html
    form_class = TorrentForm
    success_url = reverse_lazy('torrent_list')  # Cambia 'nombre_de_tu_url_de_exito' por la URL a la que quieres redirigir después de enviar el formulario

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class TorrentDetail(DetailView):
    model =  torrent

    #template_name = ""


class TorrentList(ListView):
    model = torrent
    template_name = 'torrent/torrent_list.html'
    context_object_name = 'torrents'


def download_torrent(request, torrent_id):
    torrent_obj = get_object_or_404(torrent, pk=torrent_id)
    torrent_file = torrent_obj.torrent_file
    response = FileResponse(torrent_file.open(), content_type='application/octet-stream')
    response['Content-Disposition'] = f'attachment; filename="{torrent_file.name}"'
    return response

class HomeView(ListView):
    model = torrent
    template_name = "torrent/index.html"

#funcion de busqueda
def search(request):
    query = request.GET.get("q")

    if query:
        results = torrent.objects.filter(title__icontains = query)
    else:
        results = []
    
    return render(request, "torrent/search_results.html", {"results" : results, "query" : query})

torrent/templates/torrent/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ElPiratilla</title>
    <link rel="icon" href="/static/icono.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="logo">
            <img src="/static/logo2.png" alt=" Logo">
        </div>
        <div class="search">
            <form action="{% url 'search' %}" method="GET">
                <input type="text" name="q" placeholder="Buscar...">
                <button type="submit">Buscar</button>
            </form>
        </div>
        <br>
        <br>
        
        <div class="view-all">
            <a href="{% url 'torrent_list' %}">Ver todo el catálogo</a>
        </div>
        <br>

        <div class="view-all">
            <a href="{% url 'upload_torrent' %}">Sube tu archivo!</a>
        </div>
    </div>
</body>
<style>
    body {
        margin: 0;
        padding: 0;
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: flex-start;
        background: url('/static/bg3.jpeg') no-repeat center center fixed; 
        background-size: cover; 
        overflow: hidden;
    }

    .container {
        margin-top: 2vh;
    }

    .logo img {
       
        width: 500px;
        height: auto;
        margin-top: 55px;
    }

    .search {
        margin-top: 0px;
        text-align: center;
        
    }

    .search input[type="text"] {
        padding: 10px;
        width: 400px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
    }

    .search button {
        padding: 10px 20px;
        background-color: #cd871d;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }

    .search button:hover {
        background-color: #dd402b;
    }

    .view-all {
        margin-top: 20px;
        text-align: center;
    }

    .view-all a {
        padding: 7px 20px;
        background-color: #cd871d;
        color: rgb(0, 0, 0);
        border: none;
        border-radius: 5px;
        cursor: pointer;
        text-decoration: none;
        font-size: 16px;
        font-family: 'Press Start 2P', cursive;
    }

    .view-all a:hover {
        background-color: #dd402b;
    }
</style>
</html>

torrent/templates/torrent/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultados de la búsqueda</title>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <style>
        body {
            background: url('/static/bg3.jpeg') no-repeat center center fixed; 
            font-family: 'Press Start 2P', cursive;
            margin: 0; /* Eliminar márgenes predeterminados del cuerpo */
            padding-top: 100px; /* Ajustar el espacio superior para el logo */
            text-align: center; /* Centrar el contenido */
            color: white;
            
        }

        .logo img {
            max-width: 300px; /* Tamaño máximo del logo */
            height: auto; /* Altura automática */
            margin-bottom: 20px; /* Espacio debajo del logo */
        }

        /* Agrega el resto de tu CSS aquí */
        .results-container {
            display: flex;
            justify-content: center;
            flex-wrap: wrap; /* Envolver elementos en varias filas si es necesario */
        }

        .results-list {
            list-style: none;
            padding: 0;
        }

        .result-item {
            width: 300px; /* Ancho máximo de cada elemento de resultado */
            margin: 20px; /* Espacio entre elementos */
            padding: 20px; /* Relleno interior */
            border: 1px solid #ccc; /* Borde */
            border-radius: 5px; /* Bordes redondeados */
            text-align: left; /* Alinear el texto a la izquierda */
        }

        .result-image img {
            max-width: 100%; 
            height: auto; 
            margin-bottom: 10px; 
        }

        .result-details a {
            text-decoration: none; 
            color: rgb(23, 221, 76); 
        }

        .result-details a:hover {
            color: rgb(13, 240, 47); 
        }
    </style>
</head>
<body>
    <div class="logo">
        <img src="/static/logo2.png" alt="Logo">
    </div>
    
    {% if query %}
        <h2>{{ results|length }} Resultados "{{query}}" </h2>
        <div class="results-container">
            <ul class="results-list">
                {% for result in results %}
                    <li class="result-item">
                        <div class="result-details">
                            <h3>{{ result.title }}</h3>
                            <p>{{ result.description }}</p>
                            <p>Idioma: {{ result.get_language_display }}</p>
                            <br>
                            <p><a href="{% url 'download_torrent' result.id %}">Descargar Torrent</a></p>
                        </div>
                        <div class="result-image">
                            <img src="{{ result.image.url }}" alt="{{ result.title }}">
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% else %}
        <p>No se encontraron resultados.</p>
    {% endif %}
</body>
</html>

torrent/templates/torrent/torrent_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalle de la película</title>
</head>
<body>
    <h1>Detalle de la película</h1>
    <h2>{{ pelicula.titulo }}</h2>
    <img src="{{ pelicula.imagen }}" alt="Imagen de la película">
    <p>{{ pelicula.descripcion }}</p>
    <a href="{{ pelicula.enlace_descarga }}">Descargar</a>
</body>
</html>

torrent/templates/torrent/torrent_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo el catálogo</title>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Press Start 2P', cursive;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            background: url('/static/bg3.jpeg') no-repeat center center fixed;
            background-size: cover;
        }

        .container {
            width: 80%;
            margin: 0 auto;
            background-color: #181818;
            padding: 2px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .separator {
            width: 100%;
            height: 1px;
            background-color: #fff;
            margin: 10px 0;
        }

        .navbar {
            display: flex;
            justify-content: space-between;
            align-items: center;
            width: 100%;
            padding: 20px 10px;
        }

        .logo {
            width: 200px;
            height: auto;
        }

        .navbar-text {
            color: #fff;
            font-size: 1.2rem;
        }

        .alphabet-dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #4CAF50;
            min-width: 120px;
            z-index: 1;
            border-radius: 10px;
        }

        .dropdown-content a {
            color: white;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            font-size: 0.8rem;
            cursor: pointer; /* Cambio importante: agregar cursor pointer */
        }

        .dropdown-content a:hover {
            background-color: #45a049;
        }

        .alphabet-dropdown:hover .dropdown-content {
            display: block;
        }

        .movie-list {
            margin-top: 50px;
            width: 100%;
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        .movie-item {
            width: 100%;
            background-color: #181818;
            border-radius: 10px;
            padding: 20px;
            margin-bottom: 20px;
            color: #fff;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            font-size: 0.8rem;
        }

        .movie-item h3 {
            font-size: 1rem;
            margin-bottom: 0.5rem;
        }

        .movie-item p {
            margin-bottom: 0.5rem;
            display: inline-block;
        }

        .movie-item a {
            color: #0da230;
            text-decoration: none;
            transition: color 0.3s;
            display: inline-block;
            margin-left: 10px;
        }

        .movie-item a:hover {
            color: #11b91f;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <div>
            <img src="/static/logo2.png" alt="Logo" class="logo"  >
            <span class="navbar-text">Listado de Películas</span>
            <div class="alphabet-dropdown">
                <button class="all-button">Filtrar</button>
                <div class="dropdown-content" id="alphabet-dropdown">
                    {% for letter in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' %}
                        <a>{{ letter }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    
    <div class="container">
        <div class="movie-list">
            {% for torrent in torrents %}
                <div class="movie-item" data-title="{{ torrent.title }}">
                    <h3>{{ torrent.title }}</h3>
                    <p>{{ torrent.description }}</p>
                    <p>Idioma: {{ torrent.get_language_display }}</p>
                    <p>{{ torrent.date }}</p>
                    <p>Vistas: {{ torrent.views }}</p>
                    <p><a href="{% url 'download_torrent' torrent.id %}">Descargar Torrent</a></p>
                </div>
                <div class="separator"></div>
            {% endfor %}
        </div>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const allButton = document.querySelector('.all-button');
            const movies = document.querySelectorAll('.movie-item');

            // Agregar evento de clic a cada letra
            document.querySelectorAll('.alphabet-dropdown a').forEach(letter => {
                letter.addEventListener('click', function() {
                    const selectedLetter = this.textContent;
                    filterMovies(selectedLetter);
                });
            });

            function filterMovies(letter) {
                movies.forEach(movie => {
                    const title = movie.dataset.title;
                    const normalizedTitle = title.trim().toUpperCase();
                    if (normalizedTitle.charAt(0) === letter) {
                        movie.style.display = 'block';
                    } else {
                        movie.style.display = 'none';
                    }
                });
            }

            allButton.addEventListener('click', function() {
                movies.forEach(movie => {
                    movie.style.display = 'block';
                });
            });
        });
    </script>
</body>
</html>

torrent/templates/torrent/upload_torrent.html
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <title>Subir Torrent</title>
    <style>
        body {
            background: url('/static/bg3.jpeg') no-repeat center center fixed; 
            background-color: #000;
            color: #0f0;
            font-family: 'Press Start 2P', cursive;
            text-align: center;
        }
        h1 {
            font-size: 2.5em;
            margin-top: 50px;
        }
        form {
            margin-top: 30px;
        }
        input[type="file"] {
            border: 2px solid #0f0;
            padding: 10px;
            background-color: #222;
            color: #0f0;
            font-size: 1.2em;
        }
        button[type="submit"] {
            border: 2px solid #0f0;
            padding: 10px 20px;
            background-color: #222;
            color: #0f0;
            font-size: 1.2em;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }
        button[type="submit"]:hover {
            background-color: #0f0;
            color: #000;
        }
    </style>
</head>
<body>
    <h1>Subir Torrent</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
    </form>
</body>
</html>